### ISSUE TITLE
[Bug]: Translated web page doesn't preserve hyperlink format

### ISSUE THREAD

**Issue by vanbang9710** [immersive-translate/immersive-translate#1155]
### 插件版本号 | Version

0.11.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Microsoft Edge

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

The text "[Nouga-OCR + 沉浸式翻译](https://immersivetranslate.com/en/docs/pdf/nougat/)" is translated without hyperlink format to "Nouga-OCR + Immersive Translation"

### 出现问题的网址 | URL

https://immersivetranslate.com/en/docs/pdf-helper/

### 重现步骤 | To Reproduce

- Open [this url](https://immersivetranslate.com/en/docs/pdf-helper/)
- Translate to English ![image](https://github.com/immersive-translate/immersive-translate/assets/52906188/1ea45daf-7b68-49a8-9e82-e468218dfdcf)
The result ![|50pct](https://i.imgur.com/Jl5PJ53.png)

**Comment by theowenyoung** [comment]
Yes, this is expected behavior, because the translation API we use are currently text-only translation API, which is why we give priority to recommending users to use the bilingual translation mode, so that users can click on links in the original text.

In the long run, we hope to retain the format of the original text, but this may be a challenge for us
