### ISSUE TITLE
[Bug]: Firefox无法使用DeepLX服务进行翻译

### ISSUE THREAD

**Issue by imbalaomao** [immersive-translate/immersive-translate#1460]
### 插件版本号 | Version

1.2.1

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

+ 问题描述：在Windows的Firefox浏览器（v123.0）打开Twitter，使用DeepLX翻译时，提示 **"翻译服务或网络似乎出了点问题"** ，而在Windows的Edge浏览器（v122.0.2365.52）中执行同样操作，可以正常翻译

+ 问题截图：
  - firefox截图
![图片](https://github.com/immersive-translate/immersive-translate/assets/35653686/f278160f-3496-4a11-994a-15a2f611c8d6)

  - Edge截图
![图片](https://github.com/immersive-translate/immersive-translate/assets/35653686/88ac53a4-18f5-4a9e-a9a8-54c9aa14a046)

### 出现问题的网址 | URL

https://twitter.com/home

### 补充说明 | Additional context

 已确认不是代理引起的问题，因为Clash中明确收到了来自Firefox的翻译请求
![图片](https://github.com/immersive-translate/immersive-translate/assets/35653686/cd4ce5a6-10db-4c34-bb6d-021d62fe3ee2)

**Comment by keyboard3** [comment]
看下其他浏览器上是否正常？

**Comment by bigm0re** [comment]
我更新1.2.2测试，iceweasel 123, 无法使用，提示：网络问题，无法连接到服务，请检查你的代理或本地网络连接后重试。 NetworkError when attempting to fetch resource.
我在sillytraven平台上可以调用到

**Comment by MajoranaOedipus** [comment]
I am having an almost exact issue.
The workaround is to **turn off the HTTPS-Only mode**, or switch to **Try HTTPS first, but allow connections that are not secure** in your Firefox's Privacy settings.

I have a Flask server to recieve request and forwarding it to the locally deployed LLM model service, as a proxy.
If it only listens to HTTP request, it gets something like
```
ERROR code 400, message Bad request version ('ÝÔ~D*F\'ÚÔðz¢\x0e0IÁ(\x8cÓ\x04´Û³ÇÎ\xadX2\x8cåÒN\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
```
because Firefox did an HTTP -> HTTPS upgrade,
but if the `ssl_context="adhoc"` is added in `app.run` of the Flask server, no request logged at all. Firefox aborts the request since it thinks the SSL license is not trusted?

No matter which case, Immersive Translate says `NetworkError when attempting to fetch resources`.

Exceptions are when the API url is just localhost or `192.168.*.*`, etc.

It seems like you have to choose to give up some privacy features to make it works? 

Normally when browsing sites which only supports HTTP, It can be added to **Exceptions** in the Privacy settings (equivalent to clicking "I trust the site and continue"). 
Yet I do not know why the Immersive Translate addon does *not* follow the settings. I am not an expert in JavaScript or browser.

It's there a better workaround? Can anything be done at the addon side?
