### ISSUE TITLE
可不可以加入让chatgpt翻译的功能？

### ISSUE THREAD

**Issue by ZhongoLi** [immersive-translate/immersive-translate#98]
作者您好！我对计算机相关技术完全是小白，很想知道翻译插件能不能加入让chatgpt翻译的服务，目前从我的使用感受来讲，chatgpt翻译的最自然易懂，比传统翻译服务要好许多。作者做的这个插件实在是太棒了，谢谢！

**Comment by theowenyoung** [comment]
可以，正在研究，但是估计目前也用不了，因为api限制频率，等 chatgpt plus出了之后，也许会好很多。

**Comment by seeflood** [comment]
请问有什么新进展么？或者能否使用gpt3模型?
我测试了下chatgpt翻译效果比别的好很多，非常期待这个功能！

**Comment by YoungKang1222** [comment]
目前chatgpt是翻译结果最好的，期待接入

**Comment by theowenyoung** [comment]
目前最新版本已经支持了  OpenAI GPT3.5 翻译，欢迎试用～

**Comment by YoungKang1222** [comment]
Let’s take a look at how the LLM behind ChatGPT is developed. There are already numerous technical introductions on this topic, and we will briefly describe the underlying principles. Its basis is GPT-3, or more precisely, the latest version called Da Vinci GPT-3.5. This model is first of all extremely large in scale, and its size has made miracles happen. With billions of tokens as training data, it forms a model with billions of parameters. Research has shown that universal large models will exhibit an “emergence” of certain skills once they reach a certain scale, and these emerging skills can perform well in various multi-task scenarios with minimal prompting. Previously, this phenomenon was generally attributed to the transformation of quantity into quality, and it was basically treated as a mystery. It is like saying that God’s favor is shown, or a modern version of the story of the foolish old man who moved the mountain: the modern foolish old man worked hard and moved the mountain, moving God to tears. Now it seems that it is not so mysterious: the emergence of multi-tasking skills must be based on a super-large data LLM because without LLM, there is no space to tune the model based on human preferences. Large language models learned from language sequence, and their greatest feature is their ability to generate, giving many possibilities for subsequent “chain reactions,” but only a small percentage of these possibilities are desirable and beneficial. Many generations may be shallow, empty, or even harmful. ChatGPT’s breakthrough is in the fine-tuning process, using reinforcement learning as its core, it found an effective method aligned with human preferences. This is like having a huge basin with 1000 children bathing inside, and now you want to pour out the bathwater without pouring out the children. It is almost impossible. But if you can control it roughly, the result is that the water is poured out, but 100 good children are left. The premise of doing this is that the basin must be large. Only super-large data models can do this with confidence. For example, what proportion of directly translated or question-and-answer-related data is there in normal language corpus? It’s a fraction, and when the data size is small, it’s hard to learn these skills from the sequence learning pattern. But with super-large data, the proportion multiplied by a large number creates the conditions and soil for learning. At this point, if the model is large enough, these skills will be learned implicitly. In a basic model with almost infinite generation possibilities, if enough work is not done later, the probability of generating suboptimal responses is high. Therefore, “aligning with human expectations” becomes the ultimate goal of fine-tuning. In this process, many children were also poured out, which is called the alignment tax in the literature, referring to the “tax” that must be paid to create a natural language interface model aligned with human beings. But it doesn’t matter, because people can’t see the lost treasures, as long as they see the good children, it’s fine. Large models have enough redundancy and are not afraid of filtering and pruning at all levels. In fact, it is not the large model itself that creates miracles, but the large model prepares a warm bed for miracles to happen.
在这个过程中，许多孩子也被倾泻出来，这在文献中被称为对齐税，指的是必须支付的“税”，以创建与人类对齐的自然语言接口模型。但这并不重要，因为人们看不到失去的宝藏，只要看到好孩子就可以了。大型模型具有足够的冗余，并且不怕在各个层面上进行过滤和修剪。实际上，不是大型模型本身创造了奇迹，而是大型模型为奇迹准备了一个温暖的床铺。 许多世代可能是肤浅的、空洞的，甚至是有害的。ChatGPT的突破在于微调过程，以强化学习为核心，它找到了一种与人类偏好相一致的有效方法。这就像有一个装着1000个孩子的大盆，现在你想倒掉盆里的水而不倒掉孩子。这几乎是不可能的。但如果你能粗略地控制它，结果就是水被倒掉了，但留下了100个好孩子。这样做的前提是盆必须很大。只有超大型数据模型才能有信心做到这一点。例如，在正常语料库中，直接翻译或问答相关数据的比例是多少？这只是一个分数，当数据规模很小时，很难从序列学习模式中学习这些技能。但是，有了超大型数据，比例乘以一个大数就创造了学习的条件和土壤。此时，如果模型足够大，这些技能将被隐式地学习。在一个基本模型中，几乎有无限的生成可能性，如果后期没有做足够的工作，生成次优响应的概率就很高。因此，“与人类期望一致”成为微调的最终目标。让我们来看看ChatGPT背后的LLM是如何开发的。关于这个话题已经有了许多技术介绍，我们将简要描述其基本原理。它的基础是GPT-3，更确切地说是最新版本的达芬奇GPT-3.5。首先，这个模型在规模上非常大，它的大小创造了奇迹。通过数十亿个标记作为训练数据，它形成了一个具有数十亿个参数的模型。研究表明，通用的大型模型一旦达到一定规模，就会展现出某些技能的“出现”，这些出现的技能可以在各种多任务场景中表现出色，而且只需要最少的提示。以前，这种现象通常被归因于数量转化为质量的转变，基本上被视为一个谜。就像说上帝的恩宠得到了展现，或者是愚蠢老人移山的现代版本：现代愚蠢老人努力工作，移动了山，感动了上帝。现在看来，这并不是那么神秘：多任务技能的出现必须基于超大规模的数据LLM，因为没有LLM，就没有空间根据人类偏好来调整模型。大型语言模型从语言序列中学习，它们最大的特点是生成能力，为后续的“连锁反应”提供了许多可能性，但只有其中很小一部分是理想和有益的。

翻译的语序出现问题，可以看下https://liweinlp.com/?p=10320

**Comment by julee** [comment]
> Let’s take a look at how the LLM behind ChatGPT is developed. There are already numerous technical introductions on this topic, and we will briefly describe the underlying principles. Its basis is GPT-3, or more precisely, the latest version called Da Vinci GPT-3.5. This model is first of all extremely large in scale, and its size has made miracles happen. With billions of tokens as training data, it forms a model with billions of parameters. Research has shown that universal large models will exhibit an “emergence” of certain skills once they reach a certain scale, and these emerging skills can perform well in various multi-task scenarios with minimal prompting. Previously, this phenomenon was generally attributed to the transformation of quantity into quality, and it was basically treated as a mystery. It is like saying that God’s favor is shown, or a modern version of the story of the foolish old man who moved the mountain: the modern foolish old man worked hard and moved the mountain, moving God to tears. Now it seems that it is not so mysterious: the emergence of multi-tasking skills must be based on a super-large data LLM because without LLM, there is no space to tune the model based on human preferences. Large language models learned from language sequence, and their greatest feature is their ability to generate, giving many possibilities for subsequent “chain reactions,” but only a small percentage of these possibilities are desirable and beneficial. Many generations may be shallow, empty, or even harmful. ChatGPT’s breakthrough is in the fine-tuning process, using reinforcement learning as its core, it found an effective method aligned with human preferences. This is like having a huge basin with 1000 children bathing inside, and now you want to pour out the bathwater without pouring out the children. It is almost impossible. But if you can control it roughly, the result is that the water is poured out, but 100 good children are left. The premise of doing this is that the basin must be large. Only super-large data models can do this with confidence. For example, what proportion of directly translated or question-and-answer-related data is there in normal language corpus? It’s a fraction, and when the data size is small, it’s hard to learn these skills from the sequence learning pattern. But with super-large data, the proportion multiplied by a large number creates the conditions and soil for learning. At this point, if the model is large enough, these skills will be learned implicitly. In a basic model with almost infinite generation possibilities, if enough work is not done later, the probability of generating suboptimal responses is high. Therefore, “aligning with human expectations” becomes the ultimate goal of fine-tuning. In this process, many children were also poured out, which is called the alignment tax in the literature, referring to the “tax” that must be paid to create a natural language interface model aligned with human beings. But it doesn’t matter, because people can’t see the lost treasures, as long as they see the good children, it’s fine. Large models have enough redundancy and are not afraid of filtering and pruning at all levels. In fact, it is not the large model itself that creates miracles, but the large model prepares a warm bed for miracles to happen. 在这个过程中，许多孩子也被倾泻出来，这在文献中被称为对齐税，指的是必须支付的“税”，以创建与人类对齐的自然语言接口模型。但这并不重要，因为人们看不到失去的宝藏，只要看到好孩子就可以了。大型模型具有足够的冗余，并且不怕在各个层面上进行过滤和修剪。实际上，不是大型模型本身创造了奇迹，而是大型模型为奇迹准备了一个温暖的床铺。 许多世代可能是肤浅的、空洞的，甚至是有害的。ChatGPT的突破在于微调过程，以强化学习为核心，它找到了一种与人类偏好相一致的有效方法。这就像有一个装着1000个孩子的大盆，现在你想倒掉盆里的水而不倒掉孩子。这几乎是不可能的。但如果你能粗略地控制它，结果就是水被倒掉了，但留下了100个好孩子。这样做的前提是盆必须很大。只有超大型数据模型才能有信心做到这一点。例如，在正常语料库中，直接翻译或问答相关数据的比例是多少？这只是一个分数，当数据规模很小时，很难从序列学习模式中学习这些技能。但是，有了超大型数据，比例乘以一个大数就创造了学习的条件和土壤。此时，如果模型足够大，这些技能将被隐式地学习。在一个基本模型中，几乎有无限的生成可能性，如果后期没有做足够的工作，生成次优响应的概率就很高。因此，“与人类期望一致”成为微调的最终目标。让我们来看看ChatGPT背后的LLM是如何开发的。关于这个话题已经有了许多技术介绍，我们将简要描述其基本原理。它的基础是GPT-3，更确切地说是最新版本的达芬奇GPT-3.5。首先，这个模型在规模上非常大，它的大小创造了奇迹。通过数十亿个标记作为训练数据，它形成了一个具有数十亿个参数的模型。研究表明，通用的大型模型一旦达到一定规模，就会展现出某些技能的“出现”，这些出现的技能可以在各种多任务场景中表现出色，而且只需要最少的提示。以前，这种现象通常被归因于数量转化为质量的转变，基本上被视为一个谜。就像说上帝的恩宠得到了展现，或者是愚蠢老人移山的现代版本：现代愚蠢老人努力工作，移动了山，感动了上帝。现在看来，这并不是那么神秘：多任务技能的出现必须基于超大规模的数据LLM，因为没有LLM，就没有空间根据人类偏好来调整模型。大型语言模型从语言序列中学习，它们最大的特点是生成能力，为后续的“连锁反应”提供了许多可能性，但只有其中很小一部分是理想和有益的。
> 翻译的语序出现问题，可以看下https://liweinlp.com/?p=10320

我这试了下也有这个问题。 可以新开一个 issue 吧

**Comment by theowenyoung** [comment]
我这是这样，难道是新更新了换行的规则，所以正常了？ 你们可以更新下规则试试。

<img width="830" alt="截屏2023-03-06 21 02 04" src="https://user-images.githubusercontent.com/62473795/223117651-0967f5fb-1644-4754-80f2-f5d7352d7118.png">

**Comment by YoungKang1222** [comment]
原文已经变了，目前一切正常

**Comment by julee** [comment]
> 

原文没有变。 @theowenyoung  ，用 0.2.81 版本没有问题了

**Comment by GrayXu** [comment]
respect🫡  
文档里的[openai子页面](https://immersive-translate.owenyoung.com/services/openai)也可以同步更新下
